-- 1
SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO='002'
ORDER BY ENTRANCE_DATE;

-- 2
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR
-- WHERE PROFESSOR_NAME NOT LIKE '___';
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3
SELECT PROFESSOR_NAME "교수이름" ,
EXTRACT(YEAR FROM SYSDATE) -
EXTRACT(YEAR FROM 
TO_DATE('19' || SUBSTR(PROFESSOR_SSN,1,6)))
AS "나이" 
-- EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN,1,2))
FROM TB_PROFESSOR
ORDER BY "나이" ASC;

-- 4
SELECT SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

-- 5
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) -
(EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR' ))) > 19;

-- 6
SELECT TO_CHAR(TO_DATE('20201225'),'DAY')
FROM DUAL;

-- 7
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY-MM-DD'),
TO_DATE('49/10/11','YY/MM/DD')
FROM DUAL;

-- 8
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) !='A';

-- 9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
SELECT DEPARTMENT_NO 학과번호 , COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

-- 13
SELECT DEPARTMENT_NO 학과코드명,
--COUNT( DECODE(ABSENCE_YN , 'Y' , 1) )
SUM(CASE WHEN ABSENCE_YN = 'Y' THEN 1 ELSE 0 END) 휴학생수
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14
SELECT STUDENT_NAME , COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2
ORDER BY STUDENT_NAME;

--15
SELECT SUBSTR(TERM_NO,1,4) 년도 , SUBSTR(TERM_NO,5,2) 학기
, ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY 1,2;