-- 1. 70년대 생(1970~1979) 중 여자이면서 
-- 전씨인 사원의 이름과 주민번호, 부서 명, 직급 조회
SELECT EMP_NAME , EMP_NO , DEPT_TITLE,  JOB_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE SUBSTR(EMP_NO,1,1) = '7' 
AND SUBSTR(EMP_NO,8,1) = 2
AND EMP_NAME LIKE '전%';

-- 2. 나이 상 가장 막내의 사원 코드, 사원 명, 나이, 부서 명, 직급 명 조회
SELECT * FROM
(SELECT EMP_ID, EMP_NAME ,
EXTRACT(YEAR FROM SYSDATE) -
(DECODE(SUBSTR(EMP_NO,8,1),'1',19,'2',19,20) || SUBSTR(EMP_NO,1,2)) 나이, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
ORDER BY 3)
WHERE ROWNUM = 1;

-- 3. 이름에 '형'이 들어가는 사원의 사원코드, 사원 명, 직급조회
SELECT EMP_ID, EMP_NAME , JOB_NAME
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
-- JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

-- 4. 부서코드가 D5이거나 D6인 사원의 사원 명, 직급 명, 부서 코드, 부서 명 조회
SELECT EMP_NAME , JOB_NAME , DEPT_ID, DEPT_TITLE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
-- JOIN JOB USING(JOB_CODE)
WHERE DEPT_CODE IN ('D5','D6');

-- 5. 보너스를 받는 사원의 사원 명, 부서 명, 지역 명 조회
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
LEFT JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
WHERE BONUS IS NOT NULL;

-- 6. 사원 명, 직급 명, 부서 명, 지역 명 조회
SELECT EMP_NAME , JOB_NAME , DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
LEFT JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
LEFT JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE);

-- 7. 한국이나 일본에서 근무 중인 사원의 사원 명, 부서 명, 지역 명, 국가 명 조회
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
LEFT JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
LEFT JOIN NATION N ON (L.NATIONAL_CODE = N.NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국','일본');

-- 8. 한 사원과 같은 부서에서 일하는 사원의 이름 조회
SELECT E1.EMP_NAME, E1.DEPT_CODE, E2.EMP_NAME
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.DEPT_CODE = E2.DEPT_CODE 
AND E1.EMP_ID != E2.EMP_ID
ORDER BY 1;

-- 9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원의 이름, 직급 명, 급여 조회(NVL)
SELECT EMP_NAME, JOB_NAME, NVL(SALARY,NULL)
FROM EMPLOYEE E
JOIN JOB J ON (J.JOB_CODE = E.JOB_CODE) 
WHERE BONUS IS NULL
AND E.JOB_CODE IN ('J4','J7');

-- 10. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서 명, 직급, 입사일, 순위 조회
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_CODE, HIRE_DATE, ROWNUM 순위
FROM
(SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_CODE, HIRE_DATE, ROWNUM 순위
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN JOB USING (JOB_CODE)
ORDER BY (SALARY + SALARY * NVL(BONUS,0)) * 12 DESC)
WHERE ROWNUM <= 5;

-- 11. 부서 별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 
-- 부서 명, 부서 별 급여 합계 조회
--11-1. JOIN과 HAVING 사용
--11-2. 인라인 뷰 사용
--11-3. WITH 사용

-- 11-1
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE
HAVING SUM(SALARY)> (
    SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE
);
-- 11-2
SELECT * FROM (
    SELECT DEPT_TITLE, SUM(SALARY) AS 급여합
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    GROUP BY DEPT_TITLE)
WHERE 급여합 > (SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE);
    
-- 11-3
WITH EMP_SALARY AS(
    SELECT DEPT_TITLE, SUM(SALARY) AS 급여합
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    GROUP BY DEPT_TITLE
)
SELECT * FROM EMP_SALARY
WHERE 급여합 > (SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE);

-- 12 부서 명과 부서 별 급여 조회
SELECT DEPT_TITLE, SUM(SALARY) AS 급여합
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    GROUP BY DEPT_TITLE;

-- 13 WITH을 이용하여 급여 합과 급여 평균 조회
WITH EMP_SUMMARY AS (
    SELECT SUM(SALARY), AVG(SALARY)
    FROM EMPLOYEE
)
SELECT * FROM EMP_SUMMARY;
-- 행단위는 UNION 사용
