-- 1. 학생이름과 주소지 표시, 
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 학생이름;

-- 2. 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서로 출력
SELECT STUDENT_NAME , STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN,1,6) DESC;

-- 3. 주소지가 강원도 or 경기도 학생 중
-- 1900년대 학번을 가진 학생들의 이름과 학번,주소를 이름의 오름차순으로 출력

SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) = '9'
AND( STUDENT_ADDRESS LIKE '%경기도%' 
OR STUDENT_ADDRESS LIKE '%강원도%')
ORDER BY 학생이름;

-- 4. 법학과 교수 중 가장 나이가 많은 사람부터 이름 확인 가능한 SQL 문 작성
-- 법학과의 '학과코드'는 학과 테이블을 조회 (TB_DEPARTMENT)
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR P
LEFT JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = P.DEPARTMENT_NO) 
WHERE D.DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;

-- 5. 2004년 2학기에 'C3118100' 과목을 수강한 학생들의 학점 조회
-- 학점이 높은 순으로 , 학점이 같은면 학번이 낮은 학생부터 표시
SELECT STUDENT_NO , POINT
FROM TB_GRADE
WHERE SUBSTR(TERM_NO,1,6) = '200402'
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC , STUDENT_NO ASC;

-- 6. 학생 번호 , 학생 이름, 학과 이름을 학생 이름으로 오름차순 정렬해서 출력
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

-- 7. 과목 이름과 과목의 학과 이름 출력
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO);

-- 8. 과목 별 교수 이름 출력
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_PROFESSOR P USING(DEPARTMENT_NO);

-- 9 8번의 결과 중 '인문사회'계열에 속한 교수 이름 찾기 
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS C
LEFT JOIN TB_PROFESSOR P USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 10, '음악학과' 학생들 "전체 평점" 출력
-- 평점은 소수점 1자리까지만 반올림하여 표시
SELECT S.STUDENT_NO , STUDENT_NAME, ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NAME, S.STUDENT_NO
ORDER BY S.STUDENT_NO;

-- 11. 학번이 A313047 인 학생이 학교를 안 온다
-- 학과 이름, 학생이름, 지도 교수 이름 출력
SELECT DEPARTMENT_NAME 학과이름 , STUDENT_NAME 학생이름
, PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT S USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 12. 2007년도에 '인간관계론' 과목을 수강한 학생을 찾아
-- 학생이름과 수강학기 표시
SELECT STUDENT_NAME , TERM_NO TERM_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS C USING(DEPARTMENT_NO)
WHERE SUBSTR(TERM_NO,1,4)='2007'
AND C.CLASS_NAME = '인간관계론';

-- 13. 예체능 계열 과목 중 과목 담당교수를 한 명도 배정받지 못한 과목 찾고
-- 과목 이름과 학과 이름을 출력
SELECT C.CLASS_NAME , D.DEPARTMENT_NAME
FROM TB_CLASS C
LEFT JOIN TB_CLASS_PROFESSOR CP ON(C.CLASS_NO = CP.CLASS_NO)
JOIN TB_DEPARTMENT D USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO BETWEEN 56 AND 63
AND CP.CLASS_NO IS NULL;

-- 14. 서반아어학과 학생들의 지도교수를 게시하고자 한다
-- 학생이름과 지도교수 이름을 찾고 지도 교수가 없을 경우 "지도교수 미지정"
SELECT STUDENT_NAME 학생이름 , NVL(PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.DEPARTMENT_NO = 20
ORDER BY S.STUDENT_NO ASC;

-- 15. 휴학생이 아닌 학생 중 평점 4.0이상을 찾아
-- 학번,이름,학과이름,평점 출력
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, 
D.DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
LEFT JOIN TB_GRADE G USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, D.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY STUDENT_NO;

-- 16. 환경조경학과 전공가목들의 과목 별 평점
SELECT CLASS_NO , CLASS_NAME , AVG(POINT)
FROM TB_CLASS C
JOIN TB_GRADE G USING(CLASS_NO)
WHERE C.DEPARTMENT_NO = 34
AND SUBSTR(CLASS_TYPE,1,2) = '전공'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17. 최경희 학생과 같은 과 학생들의 이름과 주소 출력
SELECT STUDENT_NAME , STUDENT_ADDRESS
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = 38;

-- 18. 국어국문학과에서 총 평점이 가장 높은 학생 이름, 학번 출력
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = 1
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (
    SELECT MAX(AVG(POINT))
    FROM TB_STUDENT
    JOIN TB_GRADE USING (STUDENT_NO)
    WHERE DEPARTMENT_NO = 1
    GROUP BY STUDENT_NO
);

-- 19. "환경조경학과"가 속한 같은 계열 학과들의 학과 별 전공과목 평점
SELECT DEPARTMENT_NAME "계열 학과명" , 
ROUND(AVG(POINT),1) "전공평점"
FROM TB_DEPARTMENT D
JOIN TB_GRADE G 
WHERE CATEGORY = '자연과학';

