-- DDL WORKBOOK

-- 1. 계열 정보를 저장할 카테고리 테이블 만들기
CREATE TABLE TB_CATEGORY(
NAME VARCHAR2(10),
USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. 과목 구분을 저장할 테이블 만들기
CREATE TABLE TB_CLASS_TYPE(
NO VARCHAR2(5) PRIMARY KEY,
NAME VARCHAR2(10)
);

-- 3. TB_CATEGORY 테이블의 NAME 컬럼에 PRIMARY KEY 생성
-- (KEY 이름을 생성하지 않아도 무방)
ALTER TABLE TB_CATEGORY
ADD PRIMARY KEY(NAME)
MODIFY NAME VATCHAR(20);

-- 4. TB_CLASS_TYPE 테이블의 NAME 컬럼에 NULL값이 들어가지 않도록 설정
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

-- 5. 두 테이블에서 컬럼 명이 NO인 것은 기존 타입을 유지하면서 크기는 10,
-- 컬럼명이 NAME인 것은 마찬가지로 기존 타입 유지하면서 크기 20으로 변경
ALTER TABLE TB_CLASS_TYPE 
MODIFY NO VARCHAR(10)
MODIFY NAME VARCHAR(20);

-- 6. 두 테이블 NO 컬럼과 NAME컬럼의 이름을 각 각 TB_를 제외한 테이블 이름이
-- 앞에 붙은 형태로 변경 (ex.CATEGORY_NAME)
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;

-- 7.TB_CATEGORY 테이블과 TB_CLASS_TYPE 테이블의 PRIMARY KEY 이름을
-- 다음과 같이 변경 
-- Primary Key의 이름은 "PK_ + 컬럼이름"으로 지정 (ex. PK_CATEGORY_NAME)
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT CATEGORY_NAME TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007174 TO PK_CLASS_TYPE_NO;

-- 8 삽입
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;

-- 9. TB_DEPARTMENT의 CATEGORY 칼럼이
-- TB_CATEGORY 테이블의 CATEGORY_NAME 컬럼을 부모값으로 참조하도록
-- FOREIGN KEY 지정
-- 이 때 KEY 이름은 FK_테이블이름_컬럼이름으로 지정한다 
-- (FK_DEPARTMENT_CATEGORY)
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
FOREIGN KEY(CATEGORY)
REFERENCES TB_CATEGORY;

-- 10. 대학교 학생들의 정보만이 포함된 학생일반정보 VIEW를 만들기
-- 관리자계정에서 GRANT CREATE VIEW TO WORKBOOK;
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
FROM TB_STUDENT;

-- 11. 대학교는 1년에 두 번씩 학과별로 학생과 지도교수가 면담 진행
-- 이를 위해 사용할 학생이름, 학과이름, 담당교수 이름 으로 구성된 VIEW 만들기
CREATE VIEW VW_지도면담 
AS SELECT STUDENT_NAME 학생이름, DEPARTMENT_NAME 학과이름,
NVL(PROFESSOR_NAME,'지도교수 없음') "지도교수 이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT D USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO);

-- 12. 모든 학과의 학과별 학생 수를 확인할 수 있도록 적절한 VIEW 작성
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(*) STUDENT_COUNT
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;

-- 13. 위애서 생성한 view를 통해 학번이 A213046인 학생의 이름을 
-- 본인 이름으로 변경한느 SQL문 작성
UPDATE VW_학생일반정보
SET 학생이름 = '크로클'
WHERE 학번 = 'A213046';

ROLLBACK;

-- 14. 13번과 같이 VIEW를 통해 데이터가 변경되는 상황 막으려면
-- VIEW를 어떻게 생성해야 하는가
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(*) STUDENT_COUNT
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME WITH READ ONLY; -- 읽기 전용
-- -> 권한부여 잘 하면 

-- 15. 최근 5년(2009,8,7,6,5)을 기준으로 수강인원 가장 많았던 3과목 찾기
-- 과목번호, 과목이름, 누적수강생수
SELECT * FROM(
SELECT CLASS_NO, CLASS_NAME, COUNT(*) "누적수강생수(명)"
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO) 
WHERE 2009 - SUBSTR(TERM_NO,1,4) < 5
GROUP BY CLASS_NO, CLASS_NAME 
ORDER BY COUNT(*) DESC)
WHERE ROWNUM <= 3;


